runtime: java17
instance_class: F2
automatic_scaling:
    target_cpu_utilization: 65
    min_instances: 1
    max_instances: 15
    target_throughput_utilization: 0.6
network: { }
resources:
    cpu: 1
    memory_gb: 2.3
    disk_size_gb: 10
entrypoint:
    class: io.samanthatobias.bookcatalogue.BookCatalogueApplication
runtime: java17
