name: Deploy to Google Cloud

on:
    push:
        branches:
        - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout code
            uses: actions/checkout@v2
            with:
                fetch-depth: 0

        -   name: Set up Google Cloud SDK
            uses: google-github-actions/setup-gcloud@v0.2.1
            with:
                project_id: ${{ secrets.GCP_PROJECT_ID }}
                service_account_key: ${{ secrets.GCP_SA_KEY }}
                export_default_credentials: true

        -   name: Alter .gcloudignore
            run: echo '!.git' > .gcloudignore # TODO: should skip this, but Dgt.skip=true later on doesnt work

        -   name: Check for changes since last deployment
            id: diff
            run: |
                DIFF=$(git diff --quiet HEAD^ HEAD -- . ':!.github' || echo "diff")
                echo "::set-output name=diff::$DIFF"

        -   name: Set up JDK 17
            uses: actions/setup-java@v2
            with:
                distribution: 'adopt'
                java-version: '17'

            # need to make target/classes/git.properties, does not work in cloud
        -   name: Build with Maven
            run: mvn package -DskipTests
            env:
                SPRING_PROFILES_ACTIVE: github

        -   name: Print working directory and list files
            run: |
                pwd
                ls -la

        -   name: Prepare app.yml
            run: |
                echo "  BASIC_AUTH_USERNAME: '${{ secrets.BASIC_AUTH_USERNAME }}'" >> app.yml
                echo "  BASIC_AUTH_PASSWORD: '${{ secrets.BASIC_AUTH_PASSWORD }}'" >> app.yml
                echo "  MAVEN_OPTS: '-Dgit.skip=true'" >> app.yml

        -   name: Deploy to App Engine
            if: steps.diff.outputs.diff == 'diff'
            run: gcloud app deploy

        -   name: Print target/classes directory and list files
            run: |
                ls -la target/classes
