name: Deploy to Google Cloud

on:
    push:
        branches:
        - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout code
            uses: actions/checkout@v2
            with:
                fetch-depth: 0  # Fetch all history

        -   name: Set up Google Cloud SDK
            uses: google-github-actions/setup-gcloud@v0.2.1
            with:
                project_id: ${{ secrets.GCP_PROJECT_ID }}
                service_account_key: ${{ secrets.GCP_SA_KEY }}
                export_default_credentials: true

        -   name: Check for changes since last deployment
            id: diff
            run: |
                DIFF=$(git diff --quiet HEAD^ HEAD -- . ':!.github' || echo "diff")
                echo "::set-output name=diff::$DIFF"

        #        -   name: Copy .git directory to project root
        #            run: |
        #                cp -R .git ./

        -   name: Print working directory and list files
            run: |
                pwd
                ls -la

        -   name: Deploy to App Engine
            if: steps.diff.outputs.diff == 'diff'
            run: gcloud app deploy
